-- ==============================================
-- V1: TuneBoard consolidated schema
-- Merged from V1~V10 during development
-- ==============================================

-- ── users ────────────────────────────────────
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    picture VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

-- ── tenants ──────────────────────────────────
CREATE TABLE tenants (
    id UUID PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_tenants_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ── lives ────────────────────────────────────
CREATE TABLE lives (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL,
    public_token VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    date DATE,
    location VARCHAR(255),
    deadline_at TIMESTAMP,
    status VARCHAR(40) NOT NULL,
    settings_json TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_lives_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

-- ── setting_sheet_submissions ────────────────
CREATE TABLE setting_sheet_submissions (
    id UUID PRIMARY KEY,
    live_id UUID NOT NULL,
    record_label VARCHAR(255) NOT NULL,
    submission_status VARCHAR(40) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_setting_sheet_submissions_live FOREIGN KEY (live_id) REFERENCES lives (id)
);

CREATE INDEX idx_setting_sheet_submissions_live_id ON setting_sheet_submissions (live_id);

-- ── song_duplicate_results ───────────────────
CREATE TABLE song_duplicate_results (
    id UUID PRIMARY KEY,
    live_id UUID NOT NULL UNIQUE,
    result_json TEXT NOT NULL,
    computed_at TIMESTAMP NOT NULL,
    submissions_fingerprint VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_song_duplicate_results_live FOREIGN KEY (live_id) REFERENCES lives (id) ON DELETE CASCADE
);

-- ── itunes_track_links ───────────────────────
CREATE TABLE itunes_track_links (
    id UUID PRIMARY KEY,
    submission_id UUID NOT NULL,
    song_title VARCHAR(500) NOT NULL,
    song_artist VARCHAR(500) NOT NULL,
    itunes_track_id VARCHAR(100) NOT NULL,
    itunes_title VARCHAR(500),
    itunes_artist VARCHAR(500),
    itunes_album_art_url VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_itunes_track_links_submission FOREIGN KEY (submission_id) REFERENCES setting_sheet_submissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_itunes_track_links_submission ON itunes_track_links (submission_id);

CREATE INDEX idx_itunes_track_links_track_id ON itunes_track_links (itunes_track_id);